services:
  my-keycloak:
    image: quay.io/keycloak/keycloak:26.3
    environment:
      KC_FEATURES: hostname:v2
      KC_HOSTNAME: https://auth.purpucle.pl
        #      KC_HOSTNAME_ADMIN_URL: https://auth.purpucle.pl 
        # KC_HOSTNAME_PORT: 443
        #     KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
        #KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: debug
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:7080/health/ready"]
#      interval: 15s
#      timeout: 2s
#      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443"]
    ports:
      - "7080:7080"
      - "7443:7443"
#    networks:
#      - local_network
#networks:
#  local_network:
#    driver: bridge
